// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALQKsrLuZfxQHSBF0-uE720x-uiUtCoIY',
    appId: '1:1002391138208:web:b087c8bba1b26464fbfec5',
    messagingSenderId: '1002391138208',
    projectId: 'chat-aa4b2',
    authDomain: 'chat-aa4b2.firebaseapp.com',
    databaseURL: 'https://chat-aa4b2-default-rtdb.firebaseio.com',
    storageBucket: 'chat-aa4b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEFx4_LbJUhdOK-h1kjsAdPeYKgSVc-N0',
    appId: '1:1002391138208:android:44b1a14e3f4c79ccfbfec5',
    messagingSenderId: '1002391138208',
    projectId: 'chat-aa4b2',
    databaseURL: 'https://chat-aa4b2-default-rtdb.firebaseio.com',
    storageBucket: 'chat-aa4b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDrAQYHnhrpKJnOIb8ZaDgKf7e014kZ7E',
    appId: '1:1002391138208:ios:5d60e8607c8fe560fbfec5',
    messagingSenderId: '1002391138208',
    projectId: 'chat-aa4b2',
    databaseURL: 'https://chat-aa4b2-default-rtdb.firebaseio.com',
    storageBucket: 'chat-aa4b2.appspot.com',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDrAQYHnhrpKJnOIb8ZaDgKf7e014kZ7E',
    appId: '1:1002391138208:ios:5d60e8607c8fe560fbfec5',
    messagingSenderId: '1002391138208',
    projectId: 'chat-aa4b2',
    databaseURL: 'https://chat-aa4b2-default-rtdb.firebaseio.com',
    storageBucket: 'chat-aa4b2.appspot.com',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALQKsrLuZfxQHSBF0-uE720x-uiUtCoIY',
    appId: '1:1002391138208:web:8f72f582321330adfbfec5',
    messagingSenderId: '1002391138208',
    projectId: 'chat-aa4b2',
    authDomain: 'chat-aa4b2.firebaseapp.com',
    databaseURL: 'https://chat-aa4b2-default-rtdb.firebaseio.com',
    storageBucket: 'chat-aa4b2.appspot.com',
  );

}